name: cd
on:
  push:
    branches: [ master ]

permissions:
  contents: read

jobs:
  cd:
    permissions:
      contents: write  # for peaceiris/actions-gh-pages to push pages branch
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Checkout
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - name: Setup node env
        uses: actions/setup-node@c6fd00ceb9747fb23ffdf72987450a2664414867 # v2.1.2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Generate
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
