name: Update Availability
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]
permissions:
  contents: read

jobs:
  update-availability:
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4
        with:
          python-version: "3.8"

      - name: Install requests
        run: pip install requests==2.27.1

      - name: Run availability check
        id: script
        run: python scripts/update-availability.py

      - name: Get Timestamp
        if: ${{ steps.script.outputs.updated }}
        id: timestamp
        run: echo ::set-output name=value::$(date +%s)

      - name: Create Pull Request
        uses: step-security/create-pull-request@50c103da2b9ca12cd5bc013fc6931051a5aa872b # v8.1.1
        if: ${{ steps.script.outputs.updated }}
        with:
          commit-message: "fix(): update availability"
          title: "fix(): update availability ${{ steps.timestamp.outputs.value }}"
          body: |
            - update availability
          branch: update-availability-${{ steps.timestamp.outputs.value }}
